#!/usr/bin/env bash
# A9: Bulk-delete 11 stale 2026-06-11 CC/QC/SD SOTA chore branches from origin
#
# Context: All 11 branches (CC1-CC4, QC1-QC4, SD2-SD4) were the SOTA
# chore work from the 2026-06-11 codex-exec session. None of their
# tip commits are merged into current origin/main (which was force-reset
# to 43abf2f). All branch tips are archived as `archive/<X>-2026-06-11`
# tags for reversibility. Local remote-tracking refs already deleted.
#
# Generated by: compose-pool/A9 subagent on 2026-07-02
# Branch created: branch-clean/A9-bulk-close-cc-qc-sd (off main@43abf2f)

set -euo pipefail

git push origin --delete \
  chore/CC1-005-sota-2026-06-11 \
  chore/CC2-005-sota-2026-06-11 \
  chore/CC3-005-sota-2026-06-11 \
  chore/CC4-005-sota-2026-06-11 \
  chore/QC1-005-sota-2026-06-11 \
  chore/QC2-005-sota-2026-06-11 \
  chore/QC3-005-sota-2026-06-11 \
  chore/QC4-005-sota-2026-06-11 \
  chore/SD2-004-sota-2026-06-11 \
  chore/SD3-004-sota-2026-06-11 \
  chore/SD4-004-sota-2026-06-11